/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import com.vigil.app.VigilClient;

class AppTest {
    @Test void vigilClientCanBeInstantiated() {
        VigilClient classUnderTest = new VigilClient();
        assertNotNull(classUnderTest, "VigilClient should instantiate");
    }
}
